- public/config/README_configuration.md
- public/config/new_config.json
public/config/new_config.json has an example config in the new format
the readme in the same directory has been largely replaced with the type, links, properties used in this new format
> schema changes for widget config

- public/js/rq_testing.js
- src/client_comms.js
- src/rq_server.js
- src/web_server.js
This will be roboquest_ui v 13.
Removed the transmission of application-level hearbeat events over the socket, to declutter the console.log output and reduce the traffic on the socket. Now relying instead on the socket.io ping and timeout mechanisms.
With the RaspPi and the browser host connected to the same wired network, camera FPS was 34 and network traffic was around 30 Mbps steady. On a Linux notebook, the rate was 32 FPS and network traffic was between 30 and 36 Mbps. Also, notebook browser showed random noise in the image as horizontal white lines. Did not investigate the cause. Connecting the notebook to house WiFi and using the RaspPi's wired network, the noise was not present and frames were 34 FPS steadily.
> Cleanup console.log output and profile camera frames

- public/js/rq_testing.js
Calculate the camera FPS received at the browser and display the result periodically using console.log.
With the RaspPi and the browser host connected to the same wired network, camera FPS was 34 and network traffic was around 30 Mbps steady. On a Linux notebook, the rate was 32 FPS and network traffic was between 30 and 36 Mbps. Also, notebook browser showed random noise in the image as horizontal white lines. Did not investigate the cause. Connecting the notebook to house WiFi and using the RaspPi's wired network, the noise was not present and frames were 34 FPS steadily.
> Added profiling of camera frames

- generate_messages.sh
- package-lock.json
- package.json
- src/client_comms.js
- src/robot_comms.js
- src/rq_server.js
- src/web_server.js
Upgraded NodeJS to the current LTS, v18.17.1.
Added the lodash.set library for setting properties in the ROS messages before publishing them.
Adjustments, refactoring, and renaming in the NodeJS components to support the new browser UI.
Tested by rebasing the branch with the new browser UI from the bill_publish_and_log branch, then running rq_core v13 on the RaspPi and roboquest_ui v13 on a file server.
The new browser UI can:
- OFF and ON charger, motors, and servos
- show the current state of the wall power, motors, servos, and charger
- control the motors with a joystick
- control the servos with sliders
- display telemetry numerical values
> v13: Log cleanup and massive refactoring for the new UI design

- src/web_server.js
This will be roboquest_ui v13.
Issue #38 
The WebServer class defines a callback function for saving the configuration file to the persistent file store using the ConfigFile.save_config() method. As a crude means of verifying the validity of the configuration file, it looked for both a widgets and a config property in the file. In v13 of roboquest_ui nothing uses the config section of the configuration and the browser doesn't include it. The check for the config property was therefore removed.
The POST request must include the Content-Type header set to "application/json" and the payload with the request must be the complete configuration as a JSON string.
Tested by starting everything and then using curl.
```
curl -X GET http://server:3456/persist/configuration.json > …
```
> v13: Removed the check for a "config" property in the configuration file

- public/js/index.js
I removed the shortcut for post to have more control and also explicitly set the contentType header + stringily the json
Tested by removing the configuration.json* files from public/persist. Clicked the save config button and confirmed the old config file was moved and a new config file was saved.
> fix encoding on save config

- public/js/wSlider.js
The implementation of the Slider widget wasn't emitting a properly formed payload with the 'servos' event. Corrected it to assemble payloads with the format:
```
{ "angle": 178, "name": "camera_pan"}
```
Tested by running rq_core and rq_ui, starting a "ros2 topic echo /servos", enabling the servos, and then wiggling the camera_pan slider. The published messages look like:
```
---                                                                                                 
header:                                                                                             
stamp:                                                                                            
sec: 1693338893                                                                                 
nanosec: 783999919 …
```
> Corrected the assembly of the event payload for the Slider widget

- public/css/index.css
- public/index.htm
- public/js/index.js
One of the simplest possible changes and PRs. Changed the text of the id=menu DIV from MENU to CONFIGURE. Also changed the ID from menu to configure for consistency.
Tested by rebuilding, starting, connecting the browser, clicking on the CONFIGURE button and cancelling the Configuration Menu.
This is Issue #36
> Renamed the MENU button at the top of the page to CONFIGURE

- public/config/README_configuration.md
- public/config/configuration.json
- public/js/wButton.js
A single key can be assigned to emulate a Button click. The configuration is described in public/config/README_configuration.md. The button uses only the keyDown event and doesn't include any values.
Keys are assigned as follows:
<period> - motors ON
<comma> - motors OFF
s - servos ON
a - servos OFF
To test, start all the application software, click the ENABLE KEYS button. Observe the Motors and Servos indicator while pressing each of the four keys.
Issue #65, related to Issue #64
> Added key event control for Button widgets

- public/css/index.css
- public/index.htm
- public/js/index.js
- public/js/rq_params.js
- src/params.js
The blank square in the top-left corner of the UI was intended as a way to add a new widget and to edit the configuration of an existing widget. It was removed because it didn't work correctly for either purpose.
New widgets can be added using the Configuration Settings. There is currently no way to edit and existing widget, beyond creating a new instance and deleting the old.
The set socket option was removed from the Configuration Settings because it was no longer needed and would likely confuse end users.
Issue #52
> Removed edit square and set socket option

- public/config/configuration.json
- public/js/index.js
- public/js/key_control.js
- public/js/rq_params.js
- public/js/wJoystick.js
- src/params.js
Optimized some code and fixed a defect in some code, in order to reduce the latency between a joystick command or key press and control of the motors.
Tested by running the containers on the RaspPi, enabling the keys, and then alternately wiggling the joystick and pressing various keys.
Issue #86
> Reduced the latency between joystick/key events and motor motion

- public/config/configuration.json
- public/js/wSlider.js
- scripts/dstart.sh
- src/robot_comms.js
Updated wSlider.js to handle both one and two attribute messages. Updated dstart.sh to set the default ROS_DOMAIN_ID to 72 instead of 0. Updated RobotComms to handle some messages without hard-coding them.
Tested by adding a slider widget for the /motor_speed topic and MotorSpeed message, then commanding the drive motors via both joystick and keys. See the rq_core PR for more details.
Requires [rq_core PR ]() and [rq_msgs PR ]().
> Updates for handling published topics without hard-coding the message

- public/index.htm
- public/js/index.js
- public/js/key_control.js
- public/js/key_help.js
- public/js/rq_params.js
Added support for managing the keys assigned to widget types Joystick, Slider, and Button. Can now add keys to widgets without any, add more keys to widgets with some, delete keys from widgets, and change the values associated with both the key press and release.
To test click Configure, then "config keys". A list of all Joystick, Slider, and Button widgets will be displayed, including an indication of those which already have some keys assigned. To change the assignments for a widget, click the Edit button on its row.
On the "Configure widget keys" dialog will appear the keys, if any, which are already assigned to the widget. The keycode column has the number of the assigned keyboard key, which is NOT the character code. The Key Name column is used to describe the assigned key and, …
> Configure, add, and remove widget keys

- public/js/key_control.js
Fixed a bug exposed when a button widget has a new keycode assigned. Since buttons don't require either downValues or upValues, but the key handler logic requires at least an empty downValues, the updated code ensures a key assignment will always have at least an empty downValues.
Tested by both adding a key to a button without any and adding a key to a widget which already has keys assigned.
See Issue #93
> Fixed the design bug related to empty downValues and upValues.

- public/js/index.js
- public/js/key_control.js
- public/js/key_help.js
After using the "config keys" facility to change the assignment of keys to widgets, clicking the Done button at the bottom of the list of widgets will now both apply the updated key assignments and save the configuration file.
Tested by changing a key assignment and by deleting a key assignment.
Issue #95
> Reload key configuration after config keys

- public/css/index.css
- public/js/index.js
- public/js/key_control.js
- public/js/rq_params.js
**Changes**
To resolve issue #72
- Made the trash highlight when a widget is hovering over it, because sometimes it was hard to know if the widget was over the trash box.
- Resolved conflicts with the stop dragging event, to make sure we weren't attempting to operate on undefined objects. (solution, exit the stop dragging event if the widget is undefined).
- Changed `.data('widget)` to `.getWidgetData()` and extended the `jQuery` class to incorporate the QR WIDGET namespace.
> #72 Delete Widget and Namespace Solutions

- public/js/index.js
- public/js/rq_params.js
- src/params.js
- src/robot_comms.js
- src/web_server.js
After changing the configuration of servos via the browser UI, clicking the Done button on the Choose servo dialog will automatically reload the servo configuration for rq_core.
Tested by clicking the button and verifying the roboquest base node existed and was restarted.
Requires [rq_core PR 50}(https://github.com/billmania/roboquest_core/pull/50).
> Implemented ability to reload the servo config after a change

- public/css/index.css
Just a simple one line fix. Note, this does not inhibit users from selecting input boxes and other things where that feature is important.
> Prevented user-select globally

- public/config/configuration.json
- public/js/rq_params.js
- src/params.js
- src/robot_comms.js
The MotorSpeed message used to set the maximum speed of the drive motors had the attribute max_speed changed to max_rpm. The motor speed slider widget in the default configuration.json was updated with this new name. Also changed the maximum and default value for the slider from 100 to 300.
Tested by starting the containers, using ros2 topic to echo the /motor_speed topic, and then moving the motor speed slider widget. Observed the correct values being published onto the topic by the NodeJS server.
This is rq_ui Issue #114 and requires both [rq_msgs PR 7]() and [rq_core PR 54](https://github.com/billmania/roboquest_core/pull/54).
> Replaced max_speed with max_rpm for motor speed slider widget

- public/js/rq_params.js
- src/config_file.js
- src/params.js
A inconsistently reproducible exists where the configuration.json file is corrupted after saving an updated version and removing power from the Rasp Pi without performing a clean shutdown. No clear cause was found for this issue. More logging and verification was added in an attempt to have more telemetry and evidence when the condition occurs.
Also, [rq_core PR 57](https://github.com/billmania/roboquest_core/pull/57) and [rq_core PR 58](https://github.com/billmania/roboquest_core/pull/58) were created to help with this condition.
https://github.com/billmania/roboquest_ui/issues/112
> Added logging and verification related to configuration.json

- public/config/README_configuration.md
- public/index.htm
- public/js/key_control.js
- public/js/key_help.js
- public/js/rq_params.js
- public/js/wJoystick.js
- public/js/widget_config.js
- src/params.js
The joystick widget can handle multiple of its configured keys depressed before any depressed key is released. The effect of the depressed keys is summed. This will work best when the upValues for each key are all zero. However, it is possible to define non-zero values for the upValues and that key can be depressed simultaneously with others, but it's not possible to undo the effect of the upValues.
As part of this change, the scale and topicPeriodS configuration options for the joystick were added to the add and reconfigure dialogs.
Covers Issue #119
> Simultaneous key presses for the joystick widget

- public/js/wJoystick.js
- public/js/widget_config.js
The recently added logic to support reconfiguring a widget did not preserve the old widget's key assignments. They are now being preserved.
Also stopped the JavaScript interval which was continuously publishing joystick values just before replacing the old joystick with the new configuration joystick. At the same time, added some logic to only publish joystick axes values when they change, intended to protect the topic and node from the high-frequency repeat of depressed keys. The interval will publish the values even when they haven't changed.
https://github.com/billmania/roboquest_ui/issues/126
> Preserve joystick key configurations after joystick reconfiguration

- package-lock.json
- package.json
- public/config/README_joystick.md
- public/config/configuration.json
- public/css/index.css
- public/js/index.js
- public/js/rq_params.js
- public/js/wJoystick.js
- public/js/wSlider.js
- public/js/widget_config.js
- scripts/release_docs.sh
- src/params.js
- src/robot_comms.js
Joystick widgets can now be removed from the UI, added, and reconfigured. Multiple joysticks can exist simultaneously. They can be configured to publish to a single topic and interface combination where two attributes of the message are populated with the x and y value. They can also be configured to replace mimic a simple slider and a servo slider. However, the joystick can only command a single servo and always returns the servo position to 0.
Added the lodash cloneDeep() function, so the robot_comms module could retrieve ROS message definitions at run-time.
Added specific documentation in README_joystick.md.
Changed the background color of the trash square, to make it obvious when a widget is about to be deleted.
TwistStamped message is no longer hard-coded in robot_comms.js. Joystick …
> Joystick widget add, delete, and reconfig

- public/css/index.css
- public/index.htm
- public/js/index.js
- public/js/rq_params.js
- src/params.js
- src/robot_comms.js
- src/web_server.js
Added a dropdown menu to choose one from up to four connected cameras.
The default camera at startup is always camera 0. There are always four choices shown in the menu (0–3) but they may not all be available. If a camera is selected from the menu but that camera isn't available, the background image will remain as the last frame from the previous camera.
The selected camera can be disconnected at run-time and the background image will cease to update. The disconnected camera will remain in the menu until the robot is rebooted. A camera can be added at run-time but it won't update the background image until the robot is rebooted.
Requires [rq_core PR 64](https://github.com/billmania/roboquest_core/pull/64)
> Choose from multiple cameras

- public/index.htm
- public/js/index.js
- public/js/robot_help.js
- public/js/rq_params.js
- src/params.js
Depends upon [rq_core PR 70](https://github.com/billmania/roboquest_core/pull/70).
This feature requires two "update software" clicks. The first will cause the updater.py script to be updated. The second will actually update the rq_ui image.
Added two buttons to the configuration menu: Reboot and Shutdown. Both choices show a list of steps to complete the action.
Depending on precise timing, a message about the reboot or shutdown may appear on the HAT UI. For the shutdown, electrical power must still be manually disconnected from the robot. After the reboot, prudence dictates a manual reload of the browser page.
https://github.com/billmania/roboquest_ui/issues/113
> Added support for REBOOT and SHUTDOWN to the configuration menu

- public/index.htm
- public/js/rq_params.js
- src/params.js
In v31 the "save config" button was accidentally removed. This change restores that functionality.
Tested by clicking the "save config" button and confirming both the entry in the console log and the timestamp change on the configuration.json file.
https://github.com/billmania/roboquest_ui/issues/143
> Restored the "save config" button

- public/css/index.css
- public/index.htm
- public/js/gamepad_mapping.js
- public/js/rq_params.js
- public/js/wGamepad.js
- public/js/widget_config.js
- src/params.js
Added better definitions for each browser, including using the names of the buttons and axes.
Tested with Chrome on ubuntu and Windows. Did not test the functionality of the triggers when they're handled as buttons.
> Basic support for Logitech F310 gamepad with Chrome

- package.xml
- public/js/rq_params.js
- public/js/wGamepad.js
- src/params.js
[RQ_ui Issue 156](https://github.com/billmania/roboquest_ui/issues/156)
Required by [rq_core PR 90](https://github.com/billmania/roboquest_core/pull/90)
More accurate scaling of the gamepad joystick values is required to fully exploit the more accurate population of Twist messages, sent by the UI.
> Changed the data type of gamepad scaling from Int to Float

- public/js/wGamepad.js
- public/js/wJoystick.js
The joystick UI widget has an interval on which it automatically publishes the current values from the joystick. When the gamepad is enabled and used to control the robot motion, the smoothness of the motion was being impacted, albeit mildly, because every three seconds the joystick was still commanding speeds of 0.
That bug was corrected and the joystick UI widget will now stop automatically publishing those zero speeds when the gamepad is enabled. Once the gamepad is disabled, the joystick resuming the automatic publishing.
https://github.com/billmania/roboquest_ui/issues/162
> Disable the UI joystick widget when the gamepad is enabled

- src/robot_comms.js
- src/ros_interfaces.js
D-PAD can be used to set a specific angle of a servo. It's not able to use angle_incr_deg or speed_dps.
For example, the following example sets three different positions of a servo, using three D-PAD buttons.
**For this fix to take effect, /opt/persist/ui/ros_interfaces.js and
/opt/persist/ui/widget_interfaces.js must be removed and then the robot rebooted.**
```
{
"row": "b12",
"name": "Pan center",
"topicDirection": "publish",
"topic": "servos",
"topicType": "rq_msgs/msg/Servos",
"topicAttribute": [
"servo1.angle_deg:90",
"servo1.command_type:1",
"header.frame_id:up"
],
"scale": [
1
]
},
```
> Gamepad D-PAD resets values when released
